export enum ResponseType {
  // User Management
  USERS_FETCHED = 'USERS_FETCHED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_UPSERTED = 'USER_UPSERTED',
  USER_NOT_CREATED = 'USER_NOT_CREATED',
  PROFILE_FETCHED = 'PROFILE_FETCHED',
  INVALID_USERNAME = 'INVALID_USERNAME',
  USERNAME_AVAILABILITY_CHECKED = 'USERNAME_AVAILABILITY_CHECKED',

  // Dashboard and Metrics
  METRICS_FETCHED = 'METRICS_FETCHED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  PROGRESS_FETCHED = 'PROGRESS_FETCHED',

  // Configuration
  CONFIG_UPDATED = 'CONFIG_UPDATED',
  CONFIGS_FETCHED = 'CONFIGS_FETCHED',

  // Resources
  RESOURCES_ALLOCATED = 'RESOURCES_ALLOCATED',

  // Auditing
  AUDIT_LOGS_FETCHED = 'AUDIT_LOGS_FETCHED',

  // Content Moderation
  MODERATION_QUEUE_FETCHED = 'MODERATION_QUEUE_FETCHED',
  CONTENT_MODERATED = 'CONTENT_MODERATED',
}
