import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import App from './App';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { ReactNode } from 'react';
import { WebSocketProvider } from '@/contexts/WebSocketContext';
import { ReduxProvider } from '@/contexts/ReduxContext';

const inter = Inter({ subsets: ['latin'], fallback: [] });

export const metadata = {
  title: 'Mr. Engineers',
  description: 'Generated by Mr. Engineers Inc.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-bgColor text-dark`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastContainer />
          <WebSocketProvider>
            <ReduxProvider>
              <App>{children}</App>
            </ReduxProvider>
          </WebSocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
