import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import toast, { Toaster } from "react-hot-toast";

import "./globals.css";
import UserContextProvider from "../context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mr. Engineers",
  description: "Generated by Mr. Engineers Inc.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <Navbar />

          {children}
          <Footer />
        </UserContextProvider>

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
