import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import App from "./App";
// import UserContextProvider from "../context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mr. Engineers",
  description: "Generated by Mr. Engineers Inc.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <UserContextProvider> */}

          <App>{children}</App>
          {/* </UserContextProvider> */}

          {/* <Toaster position="top-right" /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
