import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import Footer from '../components/Footer';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mr. Engineers",
  description: "Generated by Mr. Engineers Inc.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
