-- Convert all Postgres enum columns to TEXT (data-preserving) + drop the enum types.
-- Allowed values now live in src/constants/enums.ts + request validators.

ALTER TABLE "ActivityLog" ALTER COLUMN "device_type" DROP DEFAULT;
ALTER TABLE "ActivityLog" ALTER COLUMN "device_type" TYPE TEXT USING "device_type"::text;
ALTER TABLE "ActivityLog" ALTER COLUMN "device_type" SET DEFAULT 'WEB';
ALTER TABLE "ApprovalHistory" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Article" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Article" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Article" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "Battle" ALTER COLUMN "type" TYPE TEXT USING "type"::text;
ALTER TABLE "Battle" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Battle" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Battle" ALTER COLUMN "status" SET DEFAULT 'WAITING';
ALTER TABLE "Battle" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "BattleParticipant" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "BattleParticipant" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "BattleParticipant" ALTER COLUMN "status" SET DEFAULT 'JOINED';
ALTER TABLE "BugReport" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "BugReport" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "BugReport" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "BugReport" ALTER COLUMN "severity" DROP DEFAULT;
ALTER TABLE "BugReport" ALTER COLUMN "severity" TYPE TEXT USING "severity"::text;
ALTER TABLE "BugReport" ALTER COLUMN "severity" SET DEFAULT 'medium';
ALTER TABLE "Challenge" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "Challenge" ALTER COLUMN "category" TYPE TEXT USING "category"::text;
ALTER TABLE "Challenge" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Challenge" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Challenge" ALTER COLUMN "status" SET DEFAULT 'ACTIVE';
ALTER TABLE "ChallengeSubmission" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "CodeReview" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "CodeReview" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "CodeReview" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "Content" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Content" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Content" ALTER COLUMN "status" SET DEFAULT 'PENDING_REVIEW';
ALTER TABLE "Course" ALTER COLUMN "level" TYPE TEXT USING "level"::text;
ALTER TABLE "DailyChallenge" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "Enrollment" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Enrollment" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Enrollment" ALTER COLUMN "status" SET DEFAULT 'ENROLLED';
ALTER TABLE "FeatureRequest" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "FeatureRequest" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "FeatureRequest" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "FeatureRequest" ALTER COLUMN "priority" DROP DEFAULT;
ALTER TABLE "FeatureRequest" ALTER COLUMN "priority" TYPE TEXT USING "priority"::text;
ALTER TABLE "FeatureRequest" ALTER COLUMN "priority" SET DEFAULT 'medium';
ALTER TABLE "InternshipApplication" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "InternshipApplication" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "InternshipApplication" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "InterviewQuestion" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "Job" ALTER COLUMN "job_type" TYPE TEXT USING "job_type"::text;
ALTER TABLE "Mentorship" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Mentorship" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Mentorship" ALTER COLUMN "status" SET DEFAULT 'pending';
ALTER TABLE "Notification" ALTER COLUMN "type" TYPE TEXT USING "type"::text;
ALTER TABLE "PlacementTest" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "PlacementTest" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "PlacementTest" ALTER COLUMN "status" SET DEFAULT 'PENDING';
ALTER TABLE "Progress" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Progress" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "Progress" ALTER COLUMN "status" SET DEFAULT 'PENDING';
ALTER TABLE "Project" ALTER COLUMN "project_status" DROP DEFAULT;
ALTER TABLE "Project" ALTER COLUMN "project_status" TYPE TEXT USING "project_status"::text;
ALTER TABLE "Project" ALTER COLUMN "project_status" SET DEFAULT 'ongoing';
ALTER TABLE "Project" ALTER COLUMN "visibility" DROP DEFAULT;
ALTER TABLE "Project" ALTER COLUMN "visibility" TYPE TEXT USING "visibility"::text;
ALTER TABLE "Project" ALTER COLUMN "visibility" SET DEFAULT 'public';
ALTER TABLE "Quiz" ALTER COLUMN "type" TYPE TEXT USING "type"::text;
ALTER TABLE "Resource" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "Roadmap" ALTER COLUMN "difficulty" TYPE TEXT USING "difficulty"::text;
ALTER TABLE "StudyGroupMember" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "StudyGroupMember" ALTER COLUMN "role" TYPE TEXT USING "role"::text;
ALTER TABLE "StudyGroupMember" ALTER COLUMN "role" SET DEFAULT 'member';
ALTER TABLE "SupportTicket" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "SupportTicket" ALTER COLUMN "status" TYPE TEXT USING "status"::text;
ALTER TABLE "SupportTicket" ALTER COLUMN "status" SET DEFAULT 'open';
ALTER TABLE "SupportTicket" ALTER COLUMN "priority" DROP DEFAULT;
ALTER TABLE "SupportTicket" ALTER COLUMN "priority" TYPE TEXT USING "priority"::text;
ALTER TABLE "SupportTicket" ALTER COLUMN "priority" SET DEFAULT 'medium';
ALTER TABLE "TeamProject" ALTER COLUMN "project_status" DROP DEFAULT;
ALTER TABLE "TeamProject" ALTER COLUMN "project_status" TYPE TEXT USING "project_status"::text;
ALTER TABLE "TeamProject" ALTER COLUMN "project_status" SET DEFAULT 'ongoing';
ALTER TABLE "TeamProject" ALTER COLUMN "visibility" DROP DEFAULT;
ALTER TABLE "TeamProject" ALTER COLUMN "visibility" TYPE TEXT USING "visibility"::text;
ALTER TABLE "TeamProject" ALTER COLUMN "visibility" SET DEFAULT 'public';
ALTER TABLE "TeamProjectMember" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "TeamProjectMember" ALTER COLUMN "role" TYPE TEXT USING "role"::text;
ALTER TABLE "TeamProjectMember" ALTER COLUMN "role" SET DEFAULT 'member';
ALTER TABLE "User" ALTER COLUMN "experience_level" TYPE TEXT USING "experience_level"::text;
ALTER TABLE "user_daily_activities" ALTER COLUMN "activity_type" TYPE TEXT USING "activity_type"::text;


-- Drop the now-unused enum types
DROP TYPE "ActivityType";
DROP TYPE "ApplicationStatus";
DROP TYPE "BattleParticipantStatus";
DROP TYPE "BattleStatus";
DROP TYPE "BattleType";
DROP TYPE "ChallengeCategory";
DROP TYPE "ChallengeStatus";
DROP TYPE "CodeReviewStatus";
DROP TYPE "ContentStatus";
DROP TYPE "CourseLevel";
DROP TYPE "DeviceType";
DROP TYPE "Difficulty";
DROP TYPE "EnrollmentStatus";
DROP TYPE "ExperienceLevel";
DROP TYPE "GroupRole";
DROP TYPE "JobType";
DROP TYPE "Length";
DROP TYPE "MentorshipStatus";
DROP TYPE "NotificationType";
DROP TYPE "PlacementStatus";
DROP TYPE "Priority";
DROP TYPE "ProjectRole";
DROP TYPE "ProjectStatus";
DROP TYPE "QuizType";
DROP TYPE "ReportStatus";
DROP TYPE "RequestStatus";
DROP TYPE "Severity";
DROP TYPE "Status";
DROP TYPE "SubmissionStatus";
DROP TYPE "TicketPriority";
DROP TYPE "TicketStatus";
DROP TYPE "Visibility";
