import { test, expect } from '@playwright/test';

test.describe('Roadmap interactions tests', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  // Test configuration with multiple workers is usually defined in playwright.config.ts
  // For this specific suite, it can be triggered using `npx playwright test roadmaps-interactions --workers=30`

  test.beforeEach(async ({ page }) => {
    // Authenticate as a regular user or admin
    await page.goto('/auth/login');
    await page.fill('input[id="login-email"]', 'admin@eduscale.io');
    await page.fill('input[name="password"]', 'Admin@123'); // Adjust based on your Auth
    await page.click('button[type="submit"]');
    await page.waitForURL('**/dashboard');
  });

  test('should allow user to navigate to the Roadmaps page and view roadmaps', async ({
    page,
  }) => {
    // Navigate to Roadmaps
    await page.click('text=Roadmaps');
    await page.waitForTimeout(2000);
    // Ensure Roadmaps page is visible
    await expect(
      page.locator('h1').filter({ hasText: /Roadmap/i }),
    ).toBeVisible();

    // Ensure at least one roadmap card is loaded
    const roadmapCards = page
      .locator('.roadmap-card-class-or-generic')
      .or(page.locator('div').filter({ hasText: 'Developer Roadmap' }));
    await expect(roadmapCards.first()).toBeVisible({ timeout: 15000 });
  });

  test('should be able to create a new customized roadmap', async ({
    page,
  }) => {
    await page.goto('/career-roadmap/roadmaps'); // Adjust to actual route

    // Click create roadmap logic
    const createBtn = page.getByRole('button', { name: /Create|Add/i });
    if (await createBtn.isVisible()) {
      await createBtn.click();
      await page.fill(
        'input[placeholder="Roadmap Title"]',
        'My Custom Automated Roadmap',
      );
      await page.fill(
        'textarea[placeholder="Description"]',
        'This is generated by Playwright.',
      );
      await page.click('button:has-text("Submit"), button:has-text("Create")');
      await expect(page.getByText('My Custom Automated Roadmap')).toBeVisible();
    } else {
      console.log('Roadmap creation button not found, skipping creation step.');
    }
  });

  test('should allow bookmarking a roadmap', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    // Find bookmark button on the first roadmap
    const bookmarkBtn = page.locator('button[aria-label="Bookmark"]').first();
    if (await bookmarkBtn.isVisible()) {
      await bookmarkBtn.click();
      // Verify toast or bookmark state change
      await expect(page.locator('.toast')).toContainText(/bookmark/i);
    }
  });

  test('should allow liking a roadmap', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    // Find like button on the first roadmap
    const likeBtn = page.locator('button[aria-label="Like"]').first();

    if (await likeBtn.isVisible()) {
      await likeBtn.click();
      await page.waitForTimeout(1000);
    }
  });

  test('should comment on a roadmap and add a reply', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    // Click on the first roadmap to open its details
    const firstRoadmap = page
      .locator('a[href*="roadmap"]')
      .first()
      .or(page.getByRole('link').filter({ hasText: 'Roadmap' }).first());
    if (await firstRoadmap.isVisible()) {
      await firstRoadmap.click();

      // Locate comment input
      const commentInput = page.getByPlaceholder(/comment|reply/i);
      if (await commentInput.isVisible()) {
        await commentInput.fill('This is a test comment from Playwright!');
        await page
          .getByRole('button', { name: /post|submit|comment/i })
          .click();

        // Wait for the comment to appear
        await expect(
          page.getByText('This is a test comment from Playwright!'),
        ).toBeVisible();

        // Reply to the comment
        const replyBtn = page.getByRole('button', { name: /reply/i }).first();
        if (await replyBtn.isVisible()) {
          await replyBtn.click();
          const replyInput = page.getByPlaceholder(/reply/i);
          await replyInput.fill('Playwright test reply');
          await page
            .getByRole('button', { name: /submit reply|post/i })
            .click();
          await expect(page.getByText('Playwright test reply')).toBeVisible();
        }
      }
    }
  });
});
