import { test, expect } from '@playwright/test';
import { testUser } from './utils/testUsers';

/**
 * Roadmap social interactions, each asserted against a real outcome — the
 * API's answer to the click and what the page shows afterwards.
 *
 * Every step used to sit behind `if (await x.isVisible())` (with a
 * `.catch(() => false)` on top), and the file logged "button not found,
 * skipping" in the else branches. Selectors that no longer matched anything
 * simply turned the test into a page load. The controls asserted here are the
 * ones RoadmapCard, CommentSection and CommentItem render today:
 * `aria-label="Like" | "Bookmark" | "Comment"`, the "Write a comment..." /
 * "Write a reply..." textareas, and the "Post Comment" / "Reply" buttons.
 */
test.describe('Roadmap interactions tests', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test.beforeEach(async ({ page }) => {
    await page.goto('/auth/login');
    const admin = testUser('admin');
    await page.fill('input[id="login-email"]', admin.email);
    await page.fill('input[id="login-password"]', admin.password);
    await page.click('button[type="submit"]');
    await page.waitForURL('**/dashboard');
  });

  test('should allow user to navigate to the Roadmaps page and view roadmaps', async ({
    page,
  }) => {
    await page.goto('/career-roadmap/roadmaps');
    await expect(
      page.locator('h1').filter({ hasText: /Roadmap/i }),
    ).toBeVisible({ timeout: 20000 });

    // At least one roadmap card, identified by its social controls.
    await expect(
      page.locator('button[aria-label="Bookmark"]').first(),
    ).toBeVisible({ timeout: 15000 });
  });

  test('should be able to create a new customized roadmap', async ({
    page,
  }) => {
    await page.goto('/career-roadmap/roadmaps');

    // "Create Roadmap" navigates to /career-roadmap?create=true and opens the
    // modal.
    const createBtn = page
      .getByRole('button', { name: /Create Roadmap/i })
      .first();
    await expect(createBtn).toBeVisible({ timeout: 15000 });
    await createBtn.click();

    const title = `My Custom Automated Roadmap ${Date.now()}`;
    const titleInput = page.getByPlaceholder(/complete frontend/i);
    await expect(titleInput).toBeVisible({ timeout: 15000 });
    await titleInput.fill(title);
    await page
      .getByPlaceholder(/describe your roadmap/i)
      .fill(
        'This roadmap is generated by Playwright to prove the create flow works end to end.',
      );
    // The schema requires a category and estimated hours >= 1.
    await page
      .getByRole('combobox')
      .filter({ hasText: /select category/i })
      .click();
    await page.getByRole('option').first().click();
    await page.getByPlaceholder('e.g., 40').fill('10');

    const created = page.waitForResponse(
      (r) => r.url().includes('/roadmaps') && r.request().method() === 'POST',
      { timeout: 20000 },
    );
    await page.locator('button[type="submit"]').first().click();
    const resp = await created;
    expect(resp.status(), await resp.text()).toBeLessThan(300);
    await expect(page.getByText(title).first()).toBeVisible({
      timeout: 15000,
    });
  });

  test('should allow bookmarking a roadmap', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    const bookmarkBtn = page.locator('button[aria-label="Bookmark"]').first();
    await expect(bookmarkBtn).toBeVisible({ timeout: 15000 });
    const saved = page.waitForResponse(
      (r) => /\/roadmaps\/[^/]+\/bookmark/.test(r.url()),
      { timeout: 15000 },
    );
    await bookmarkBtn.click();
    const resp = await saved;
    expect(resp.status(), await resp.text()).toBeLessThan(300);
  });

  test('should allow liking a roadmap', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    const likeBtn = page.locator('button[aria-label="Like"]').first();
    await expect(likeBtn).toBeVisible({ timeout: 15000 });
    const saved = page.waitForResponse(
      (r) => /\/roadmaps\/[^/]+\/like/.test(r.url()),
      { timeout: 15000 },
    );
    await likeBtn.click();
    const resp = await saved;
    expect(resp.status(), await resp.text()).toBeLessThan(300);
  });

  test('should comment on a roadmap and add a reply', async ({ page }) => {
    await page.goto('/career-roadmap/roadmaps');

    // The card's Comment button routes to the roadmap with the discussion
    // open.
    const commentBtn = page.locator('button[aria-label="Comment"]').first();
    await expect(commentBtn).toBeVisible({ timeout: 15000 });
    await commentBtn.click();
    await page.waitForURL(/\/career-roadmap\/[^/?]+/, { timeout: 15000 });

    const commentInput = page.getByPlaceholder('Write a comment...');
    await expect(commentInput).toBeVisible({ timeout: 15000 });
    const comment = `This is a test comment from Playwright ${Date.now()}`;
    await commentInput.fill(comment);
    await page.getByRole('button', { name: 'Post Comment' }).click();
    await expect(page.getByText(comment)).toBeVisible({ timeout: 15000 });

    // Reply to it. The toggle and the submit are both labelled "Reply"; the
    // submit is the one inside the reply form, next to its textarea.
    const replyToggle = page
      .getByRole('button', { name: 'Reply', exact: true })
      .first();
    await expect(replyToggle).toBeVisible();
    await replyToggle.click();
    const replyInput = page.getByPlaceholder('Write a reply...');
    await expect(replyInput).toBeVisible();
    const reply = `Playwright test reply ${Date.now()}`;
    await replyInput.fill(reply);
    await replyInput
      .locator('..')
      .getByRole('button', { name: 'Reply', exact: true })
      .click();
    await expect(page.getByText(reply)).toBeVisible({ timeout: 15000 });
  });
});
