name: Get Code Diff and Upload Artifact 🚀

on:
  push:
    branches:
      - main
      - feature/** # Triggers on pushes to 'main' and any 'feature' branches
  pull_request:
    branches:
      - main
      - feature/** # Triggers on PRs to 'main' and 'feature' branches

jobs:
  get_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get code changes
        id: code-changes
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > code_diff.txt
          else
            git diff ${{ github.event.before }} ${{ github.event.after }} > code_diff.txt
          fi
          
      - name: Upload diff as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-changes-diff
          path: code_diff.txt
